-- phase 1 exploratory analysis
-- 1. total revenue generated by food delivery app
use food_app_project;
SELECT SUM(order_amount - discount) AS total_revenue
FROM orders;
-- 2. total order per city
SELECT r.city,
  COUNT(o.order_id) AS total_orders
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
order by total_orders desc;
-- 3. top 10 customers by total spending
SELECT c.customer_id,
  c.name,
  SUM(o.order_amount - o.discount) AS total_spent
FROM orders o
  JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id,
  c.name
ORDER BY total_spent DESC
LIMIT 10;
-- phase 2 cutomer segmentation
-- 4. cutomer category (golden, silver, bronze)
SELECT customer_category,
  COUNT(*) AS total_customers,
  SUM(total_spent) AS category_revenue
FROM (
    SELECT c.customer_id,
      SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_spent,
      CASE
        WHEN SUM(o.order_amount - IFNULL(o.discount, 0)) >= 1000 THEN 'golden'
        WHEN SUM(o.order_amount - IFNULL(o.discount, 0)) >= 500 THEN 'silver'
        ELSE 'bronze'
      END AS customer_category
    FROM orders o
      JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id
  ) t
GROUP BY customer_category;
-- phase 3 restaurant performance
-- 5. top 10 restaurants by revenue
SELECT r.restaurant_id,
  r.restaurant_name,
  SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_revenue
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id,
  r.restaurant_name
ORDER BY total_revenue DESC
LIMIT 10;
-- 6. average rating vs revenue 
SELECT r.rating,
  AVG(o.order_amount - IFNULL(o.discount, 0)) AS avg_revenue
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.rating
ORDER BY r.rating DESC;
--phase 4 delivery analysis
-- 7. average delivery time by city
SELECT r.city,
  AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time ASC;
-- 8. late delivery which are above 45 minutes
SELECT o.order_id,
  c.name AS customer_name,
  r.restaurant_name,
  o.delivery_time
FROM orders o
  JOIN customers c ON o.customer_id = c.customer_id
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time > 45;
-- phase 5 payment and discount analysis
-- 9. payment method distribution
SELECT payment_method,
  COUNT(order_id) AS total_orders
FROM orders
GROUP BY payment_method
ORDER BY total_orders DESC;
-- 10. discount impact on revenue
SELECT CASE
    WHEN discount IS NULL
    OR discount = 0 THEN 'No Discount'
    WHEN discount > 0
    AND discount <= 50 THEN '0-50'
    WHEN discount > 50
    AND discount <= 100 THEN '50-100'
    ELSE '100+'
  END AS discount_range,
  COUNT(order_id) AS total_orders,
  SUM(order_amount) AS total_revenue_before_discount,
  SUM(order_amount - IFNULL(discount, 0)) AS total_revenue_after_discount,
  SUM(IFNULL(discount, 0)) AS total_discount_given,
  ROUND(
    100 * SUM(IFNULL(discount, 0)) / SUM(order_amount),
    2
  ) AS discount_pct
FROM orders
GROUP BY discount_range
ORDER BY total_revenue_after_discount DESC;
--phase 6  advanced sql
-- 11. monthly revenue using cte
WITH monthly_revenue AS (
  SELECT DATE_FORMAT(order_date, '%Y-%m') AS month,
    SUM(order_amount - IFNULL(discount, 0)) AS total_revenue
  FROM orders
  GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT *
FROM monthly_revenue
ORDER BY month;
-- 12. rank restaurants as per revenue(using window function)
SELECT r.restaurant_id,
  r.restaurant_name,
  SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_revenue,
  RANK() OVER (
    ORDER BY SUM(o.order_amount - IFNULL(o.discount, 0)) DESC
  ) AS revenue_rank
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id,
  r.restaurant_name
ORDER BY total_revenue DESC;
-- 13. get above average restaurants using subquery
SELECT r.restaurant_id,
  r.restaurant_name,
  SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_revenue
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id,
  r.restaurant_name
HAVING total_revenue > (
    SELECT AVG(total_revenue)
    FROM (
        SELECT SUM(o2.order_amount - IFNULL(o2.discount, 0)) AS total_revenue
        FROM orders o2
        GROUP BY o2.restaurant_id
      ) avg_revenue
  );
-- phase 7 database objects
-- 14. create view for revenue
CREATE VIEW restaurant_revenue AS
SELECT r.restaurant_id,
  r.restaurant_name,
  SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_revenue
FROM orders o
  JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id,
  r.restaurant_name,
  r.city;
-- 15.  stored procedure to get top n restraurants without using limit
CREATE PROCEDURE get_top_restaurants(IN top_n INT) BEGIN
SELECT restaurant_id,
  restaurant_name,
  total_revenue
FROM (
    SELECT r.restaurant_id,
      r.restaurant_name,
      SUM(o.order_amount - IFNULL(o.discount, 0)) AS total_revenue,
      DENSE_RANK() OVER (
        ORDER BY SUM(o.order_amount - IFNULL(o.discount, 0)) DESC
      ) AS rnk
    FROM orders o
      JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id,
      r.restaurant_name
  ) ranked
WHERE rnk <= top_n;
END;
CALL get_top_restaurants(10);
-- phase 8 performance optimization
-- 16. index on order date
CREATE INDEX idx_order_date ON orders(order_date);
-- 17. index on customer name
CREATE INDEX idx_customer_name ON customers(name);
-- 18. index on restaurant name
CREATE INDEX idx_restaurant_name ON restaurants(restaurant_name);
-- phase 9 automatic logic
-- 19. create auto log high value order
CREATE TABLE high_value_orders (
  log_id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT,
  customer_id INT,
  restaurant_id INT,
  order_amount DECIMAL(10, 2),
  log_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER log_high_value_order
AFTER
INSERT ON orders FOR EACH ROW BEGIN IF NEW.order_amount > 1000 THEN
INSERT INTO high_value_orders (
    order_id,
    customer_id,
    restaurant_id,
    order_amount
  )
VALUES (
    NEW.order_id,
    NEW.customer_id,
    NEW.restaurant_id,
    NEW.order_amount
  );
END IF;
END;
insert into orders
values (
    1010,
    231,
    138,
    '2024-01-01',
    1200.00,
    100.00,
    'Credit Card',
    30
  );
insert into orders
values (
    1011,
    232,
    139,
    '2024-01-02',
    8000.00,
    50.00,
    'Cash',
    25
  );
-- 20. create trigger to prevent negative discount
CREATE TRIGGER prevent_negative_discount BEFORE
INSERT ON orders FOR EACH ROW BEGIN IF NEW.discount < 0 THEN
Set new.discount = 0;
END IF;
END;
insert into orders
values (
    1014,
    231,
    138,
    '2024-01-03',
    500.00,
    -20.00,
    'UPI',
    20
  );
select *
from orders
where order_id = 1014;
-- 21. delivery delay warning table
CREATE TABLE delivery_delay_warnings (
  warning_id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT,
  customer_id INT,
  restaurant_id INT,
  delivery_time INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
create trigger log_delivery_delay
AFTER
INSERT ON orders FOR EACH ROW BEGIN IF NEW.delivery_time > 45 THEN
INSERT INTO delivery_delay_warnings (
    order_id,
    customer_id,
    restaurant_id,
    delivery_time
  )
VALUES (
    NEW.order_id,
    NEW.customer_id,
    NEW.restaurant_id,
    NEW.delivery_time
  );
END IF;
END;
insert into orders
values (
    1016,
    231,
    138,
    '2024-01-04',
    600.00,
    30.00,
    'Credit Card',
    55
  );
